kind: Service
apiVersion: v1
metadata:
  name: my-app-service
  namespace: default
spec:
  selector:
    app: my-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
